BEGIN;

CREATE TABLE IF NOT EXISTS public.outbox_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  outbox_id uuid NOT NULL,
  topic text NOT NULL,
  partition_key text NOT NULL,
  attempt_number integer NOT NULL CHECK (attempt_number >= 1),
  outcome text NOT NULL CHECK (outcome IN ('published','retry','dead_letter')),
  provider text,
  capability text,
  operation text,
  duration_ms integer CHECK (duration_ms IS NULL OR duration_ms >= 0),
  retryable boolean,
  ambiguous boolean,
  http_status integer CHECK (http_status IS NULL OR http_status BETWEEN 100 AND 599),
  provider_code text,
  error_class text,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (outbox_id, attempt_number)
);

CREATE INDEX IF NOT EXISTS outbox_attempts_occurred_idx
  ON public.outbox_attempts (occurred_at DESC);

CREATE INDEX IF NOT EXISTS outbox_attempts_route_idx
  ON public.outbox_attempts (
    provider,
    capability,
    operation,
    outcome,
    occurred_at DESC
  );

CREATE INDEX IF NOT EXISTS outbox_attempts_topic_idx
  ON public.outbox_attempts (topic, outcome, occurred_at DESC);

COMMIT;
